### YamlMime:ManagedReference
items:
- uid: AccoRevit.Addin.Config.Logging
  commentId: N:AccoRevit.Addin.Config.Logging
  id: AccoRevit.Addin.Config.Logging
  children:
  - AccoRevit.Addin.Config.Logging.ExceptionHooks
  - AccoRevit.Addin.Config.Logging.HubTextWriter
  - AccoRevit.Addin.Config.Logging.IExceptionHooks
  - AccoRevit.Addin.Config.Logging.LogHub
  - AccoRevit.Addin.Config.Logging.LoggerConfiguration
  langs:
  - csharp
  - vb
  name: AccoRevit.Addin.Config.Logging
  nameWithType: AccoRevit.Addin.Config.Logging
  fullName: AccoRevit.Addin.Config.Logging
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: AccoRevit.Addin.Config.Logging.IExceptionHooks
  commentId: T:AccoRevit.Addin.Config.Logging.IExceptionHooks
  parent: AccoRevit.Addin.Config.Logging
  isExternal: true
  href: AccoRevit.Addin.Config.Logging.IExceptionHooks.html
  name: IExceptionHooks
  nameWithType: IExceptionHooks
  fullName: AccoRevit.Addin.Config.Logging.IExceptionHooks
- uid: AccoRevit.Addin.Config.Logging.ExceptionHooks
  commentId: T:AccoRevit.Addin.Config.Logging.ExceptionHooks
  isExternal: true
  href: AccoRevit.Addin.Config.Logging.ExceptionHooks.html
  name: ExceptionHooks
  nameWithType: ExceptionHooks
  fullName: AccoRevit.Addin.Config.Logging.ExceptionHooks
- uid: AccoRevit.Addin.Config.Logging.HubTextWriter
  commentId: T:AccoRevit.Addin.Config.Logging.HubTextWriter
  isExternal: true
  href: AccoRevit.Addin.Config.Logging.HubTextWriter.html
  name: HubTextWriter
  nameWithType: HubTextWriter
  fullName: AccoRevit.Addin.Config.Logging.HubTextWriter
- uid: AccoRevit.Addin.Config.Logging.LoggerConfiguration
  commentId: T:AccoRevit.Addin.Config.Logging.LoggerConfiguration
  parent: AccoRevit.Addin.Config.Logging
  isExternal: true
  href: AccoRevit.Addin.Config.Logging.LoggerConfiguration.html
  name: LoggerConfiguration
  nameWithType: LoggerConfiguration
  fullName: AccoRevit.Addin.Config.Logging.LoggerConfiguration
- uid: AccoRevit.Addin.Config.Logging.LogHub
  commentId: T:AccoRevit.Addin.Config.Logging.LogHub
  isExternal: true
  href: AccoRevit.Addin.Config.Logging.LogHub.html
  name: LogHub
  nameWithType: LogHub
  fullName: AccoRevit.Addin.Config.Logging.LogHub
- uid: AccoRevit.Addin.Config.Logging
  commentId: N:AccoRevit.Addin.Config.Logging
  isExternal: true
  href: AccoRevit.html
  name: AccoRevit.Addin.Config.Logging
  nameWithType: AccoRevit.Addin.Config.Logging
  fullName: AccoRevit.Addin.Config.Logging
  spec.csharp:
  - uid: AccoRevit
    name: AccoRevit
    isExternal: true
    href: AccoRevit.html
  - name: .
  - uid: AccoRevit.Addin
    name: Addin
    isExternal: true
    href: AccoRevit.Addin.html
  - name: .
  - uid: AccoRevit.Addin.Config
    name: Config
    isExternal: true
    href: AccoRevit.Addin.Config.html
  - name: .
  - uid: AccoRevit.Addin.Config.Logging
    name: Logging
    isExternal: true
    href: AccoRevit.Addin.Config.Logging.html
  spec.vb:
  - uid: AccoRevit
    name: AccoRevit
    isExternal: true
    href: AccoRevit.html
  - name: .
  - uid: AccoRevit.Addin
    name: Addin
    isExternal: true
    href: AccoRevit.Addin.html
  - name: .
  - uid: AccoRevit.Addin.Config
    name: Config
    isExternal: true
    href: AccoRevit.Addin.Config.html
  - name: .
  - uid: AccoRevit.Addin.Config.Logging
    name: Logging
    isExternal: true
    href: AccoRevit.Addin.Config.Logging.html
