### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Json
  commentId: N:Microsoft.Extensions.Configuration.Json
  id: Microsoft.Extensions.Configuration.Json
  children:
  - Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  - Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  - Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider
  - Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Json
  nameWithType: Microsoft.Extensions.Configuration.Json
  fullName: Microsoft.Extensions.Configuration.Json
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
  isExternal: true
  href: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.html
  name: JsonConfigurationProvider
  nameWithType: JsonConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
  parent: Microsoft.Extensions.Configuration.Json
  isExternal: true
  href: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.html
  name: JsonConfigurationSource
  nameWithType: JsonConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Json.JsonConfigurationSource
- uid: Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider
  isExternal: true
  href: Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider.html
  name: JsonStreamConfigurationProvider
  nameWithType: JsonStreamConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource
  parent: Microsoft.Extensions.Configuration.Json
  isExternal: true
  href: Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource.html
  name: JsonStreamConfigurationSource
  nameWithType: JsonStreamConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource
- uid: Microsoft.Extensions.Configuration.Json
  commentId: N:Microsoft.Extensions.Configuration.Json
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Extensions.Configuration.Json
  nameWithType: Microsoft.Extensions.Configuration.Json
  fullName: Microsoft.Extensions.Configuration.Json
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Configuration.html
  - name: .
  - uid: Microsoft.Extensions.Configuration.Json
    name: Json
    isExternal: true
    href: Microsoft.Extensions.Configuration.Json.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Configuration.html
  - name: .
  - uid: Microsoft.Extensions.Configuration.Json
    name: Json
    isExternal: true
    href: Microsoft.Extensions.Configuration.Json.html
