### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.UserSecrets
  commentId: N:Microsoft.Extensions.Configuration.UserSecrets
  id: Microsoft.Extensions.Configuration.UserSecrets
  children:
  - Microsoft.Extensions.Configuration.UserSecrets.PathHelper
  - Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.UserSecrets
  nameWithType: Microsoft.Extensions.Configuration.UserSecrets
  fullName: Microsoft.Extensions.Configuration.UserSecrets
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.Extensions.Configuration.UserSecrets.PathHelper
  commentId: T:Microsoft.Extensions.Configuration.UserSecrets.PathHelper
  isExternal: true
  href: Microsoft.Extensions.Configuration.UserSecrets.PathHelper.html
  name: PathHelper
  nameWithType: PathHelper
  fullName: Microsoft.Extensions.Configuration.UserSecrets.PathHelper
- uid: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute
  commentId: T:Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute
  isExternal: true
  href: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute.html
  name: UserSecretsIdAttribute
  nameWithType: UserSecretsIdAttribute
  fullName: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute
