### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAPICodePack.ApplicationServices
  commentId: N:Microsoft.WindowsAPICodePack.ApplicationServices
  id: Microsoft.WindowsAPICodePack.ApplicationServices
  children:
  - Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRecoveryException
  - Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRestartRecoveryManager
  - Microsoft.WindowsAPICodePack.ApplicationServices.BatteryState
  - Microsoft.WindowsAPICodePack.ApplicationServices.ExecutionStates
  - Microsoft.WindowsAPICodePack.ApplicationServices.PowerManager
  - Microsoft.WindowsAPICodePack.ApplicationServices.PowerManagerException
  - Microsoft.WindowsAPICodePack.ApplicationServices.PowerPersonality
  - Microsoft.WindowsAPICodePack.ApplicationServices.PowerSource
  - Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryCallback
  - Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryData
  - Microsoft.WindowsAPICodePack.ApplicationServices.RecoverySettings
  - Microsoft.WindowsAPICodePack.ApplicationServices.RestartRestrictions
  - Microsoft.WindowsAPICodePack.ApplicationServices.RestartSettings
  langs:
  - csharp
  - vb
  name: Microsoft.WindowsAPICodePack.ApplicationServices
  nameWithType: Microsoft.WindowsAPICodePack.ApplicationServices
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRecoveryException
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRecoveryException
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRecoveryException.html
  name: ApplicationRecoveryException
  nameWithType: ApplicationRecoveryException
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRecoveryException
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRestartRecoveryManager
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRestartRecoveryManager
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRestartRecoveryManager.html
  name: ApplicationRestartRecoveryManager
  nameWithType: ApplicationRestartRecoveryManager
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.ApplicationRestartRecoveryManager
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryCallback
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryCallback
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryCallback.html
  name: RecoveryCallback
  nameWithType: RecoveryCallback
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryCallback
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryData
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryData
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryData.html
  name: RecoveryData
  nameWithType: RecoveryData
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.RecoveryData
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.RecoverySettings
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.RecoverySettings
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.RecoverySettings.html
  name: RecoverySettings
  nameWithType: RecoverySettings
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.RecoverySettings
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.RestartRestrictions
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.RestartRestrictions
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.RestartRestrictions.html
  name: RestartRestrictions
  nameWithType: RestartRestrictions
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.RestartRestrictions
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.RestartSettings
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.RestartSettings
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.RestartSettings.html
  name: RestartSettings
  nameWithType: RestartSettings
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.RestartSettings
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.BatteryState
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.BatteryState
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.BatteryState.html
  name: BatteryState
  nameWithType: BatteryState
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.BatteryState
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.ExecutionStates
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.ExecutionStates
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.ExecutionStates.html
  name: ExecutionStates
  nameWithType: ExecutionStates
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.ExecutionStates
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.PowerManager
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.PowerManager
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.PowerManager.html
  name: PowerManager
  nameWithType: PowerManager
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.PowerManager
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.PowerManagerException
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.PowerManagerException
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.PowerManagerException.html
  name: PowerManagerException
  nameWithType: PowerManagerException
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.PowerManagerException
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.PowerPersonality
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.PowerPersonality
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.PowerPersonality.html
  name: PowerPersonality
  nameWithType: PowerPersonality
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.PowerPersonality
- uid: Microsoft.WindowsAPICodePack.ApplicationServices.PowerSource
  commentId: T:Microsoft.WindowsAPICodePack.ApplicationServices.PowerSource
  parent: Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.WindowsAPICodePack.ApplicationServices.PowerSource.html
  name: PowerSource
  nameWithType: PowerSource
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices.PowerSource
- uid: Microsoft.WindowsAPICodePack.ApplicationServices
  commentId: N:Microsoft.WindowsAPICodePack.ApplicationServices
  isExternal: true
  href: Microsoft.html
  name: Microsoft.WindowsAPICodePack.ApplicationServices
  nameWithType: Microsoft.WindowsAPICodePack.ApplicationServices
  fullName: Microsoft.WindowsAPICodePack.ApplicationServices
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.WindowsAPICodePack
    name: WindowsAPICodePack
    isExternal: true
    href: Microsoft.WindowsAPICodePack.html
  - name: .
  - uid: Microsoft.WindowsAPICodePack.ApplicationServices
    name: ApplicationServices
    isExternal: true
    href: Microsoft.WindowsAPICodePack.ApplicationServices.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.WindowsAPICodePack
    name: WindowsAPICodePack
    isExternal: true
    href: Microsoft.WindowsAPICodePack.html
  - name: .
  - uid: Microsoft.WindowsAPICodePack.ApplicationServices
    name: ApplicationServices
    isExternal: true
    href: Microsoft.WindowsAPICodePack.ApplicationServices.html
