### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  id: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.BinderOptions
  - Microsoft.Extensions.Configuration.ChainedBuilderExtensions
  - Microsoft.Extensions.Configuration.ChainedConfigurationProvider
  - Microsoft.Extensions.Configuration.ChainedConfigurationSource
  - Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
  - Microsoft.Extensions.Configuration.ConfigurationBinder
  - Microsoft.Extensions.Configuration.ConfigurationBuilder
  - Microsoft.Extensions.Configuration.ConfigurationDebugViewContext
  - Microsoft.Extensions.Configuration.ConfigurationExtensions
  - Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  - Microsoft.Extensions.Configuration.ConfigurationKeyNameAttribute
  - Microsoft.Extensions.Configuration.ConfigurationManager
  - Microsoft.Extensions.Configuration.ConfigurationPath
  - Microsoft.Extensions.Configuration.ConfigurationProvider
  - Microsoft.Extensions.Configuration.ConfigurationReloadToken
  - Microsoft.Extensions.Configuration.ConfigurationRoot
  - Microsoft.Extensions.Configuration.ConfigurationRootExtensions
  - Microsoft.Extensions.Configuration.ConfigurationSection
  - Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
  - Microsoft.Extensions.Configuration.FileConfigurationExtensions
  - Microsoft.Extensions.Configuration.FileConfigurationProvider
  - Microsoft.Extensions.Configuration.FileConfigurationSource
  - Microsoft.Extensions.Configuration.FileLoadExceptionContext
  - Microsoft.Extensions.Configuration.IConfiguration
  - Microsoft.Extensions.Configuration.IConfigurationBuilder
  - Microsoft.Extensions.Configuration.IConfigurationManager
  - Microsoft.Extensions.Configuration.IConfigurationProvider
  - Microsoft.Extensions.Configuration.IConfigurationRoot
  - Microsoft.Extensions.Configuration.IConfigurationSection
  - Microsoft.Extensions.Configuration.IConfigurationSource
  - Microsoft.Extensions.Configuration.JsonConfigurationExtensions
  - Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  - Microsoft.Extensions.Configuration.StreamConfigurationProvider
  - Microsoft.Extensions.Configuration.StreamConfigurationSource
  - Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.Extensions.Configuration.ConfigurationDebugViewContext
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationDebugViewContext
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationDebugViewContext.html
  name: ConfigurationDebugViewContext
  nameWithType: ConfigurationDebugViewContext
  fullName: Microsoft.Extensions.Configuration.ConfigurationDebugViewContext
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationExtensions.html
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyNameAttribute
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationKeyNameAttribute
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationKeyNameAttribute.html
  name: ConfigurationKeyNameAttribute
  nameWithType: ConfigurationKeyNameAttribute
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyNameAttribute
- uid: Microsoft.Extensions.Configuration.ConfigurationPath
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationPath
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationPath.html
  name: ConfigurationPath
  nameWithType: ConfigurationPath
  fullName: Microsoft.Extensions.Configuration.ConfigurationPath
- uid: Microsoft.Extensions.Configuration.ConfigurationRootExtensions
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationRootExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationRootExtensions.html
  name: ConfigurationRootExtensions
  nameWithType: ConfigurationRootExtensions
  fullName: Microsoft.Extensions.Configuration.ConfigurationRootExtensions
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.IConfiguration.html
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
- uid: Microsoft.Extensions.Configuration.IConfigurationBuilder
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationBuilder
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.IConfigurationBuilder.html
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: Microsoft.Extensions.Configuration.IConfigurationBuilder
- uid: Microsoft.Extensions.Configuration.IConfigurationManager
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationManager
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.IConfigurationManager.html
  name: IConfigurationManager
  nameWithType: IConfigurationManager
  fullName: Microsoft.Extensions.Configuration.IConfigurationManager
- uid: Microsoft.Extensions.Configuration.IConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.IConfigurationProvider.html
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.IConfigurationProvider
- uid: Microsoft.Extensions.Configuration.IConfigurationRoot
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationRoot
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.IConfigurationRoot.html
  name: IConfigurationRoot
  nameWithType: IConfigurationRoot
  fullName: Microsoft.Extensions.Configuration.IConfigurationRoot
- uid: Microsoft.Extensions.Configuration.IConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSection
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.IConfigurationSection.html
  name: IConfigurationSection
  nameWithType: IConfigurationSection
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection
- uid: Microsoft.Extensions.Configuration.IConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSource
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.IConfigurationSource.html
  name: IConfigurationSource
  nameWithType: IConfigurationSource
  fullName: Microsoft.Extensions.Configuration.IConfigurationSource
- uid: Microsoft.Extensions.Configuration.BinderOptions
  commentId: T:Microsoft.Extensions.Configuration.BinderOptions
  isExternal: true
  href: Microsoft.Extensions.Configuration.BinderOptions.html
  name: BinderOptions
  nameWithType: BinderOptions
  fullName: Microsoft.Extensions.Configuration.BinderOptions
- uid: Microsoft.Extensions.Configuration.ConfigurationBinder
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationBinder
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationBinder.html
  name: ConfigurationBinder
  nameWithType: ConfigurationBinder
  fullName: Microsoft.Extensions.Configuration.ConfigurationBinder
- uid: Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions.html
  name: CommandLineConfigurationExtensions
  nameWithType: CommandLineConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.ChainedBuilderExtensions
  commentId: T:Microsoft.Extensions.Configuration.ChainedBuilderExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ChainedBuilderExtensions.html
  name: ChainedBuilderExtensions
  nameWithType: ChainedBuilderExtensions
  fullName: Microsoft.Extensions.Configuration.ChainedBuilderExtensions
- uid: Microsoft.Extensions.Configuration.ChainedConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.ChainedConfigurationProvider
  isExternal: true
  href: Microsoft.Extensions.Configuration.ChainedConfigurationProvider.html
  name: ChainedConfigurationProvider
  nameWithType: ChainedConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.ChainedConfigurationProvider
- uid: Microsoft.Extensions.Configuration.ChainedConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.ChainedConfigurationSource
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ChainedConfigurationSource.html
  name: ChainedConfigurationSource
  nameWithType: ChainedConfigurationSource
  fullName: Microsoft.Extensions.Configuration.ChainedConfigurationSource
- uid: Microsoft.Extensions.Configuration.ConfigurationBuilder
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationBuilder
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationBuilder.html
  name: ConfigurationBuilder
  nameWithType: ConfigurationBuilder
  fullName: Microsoft.Extensions.Configuration.ConfigurationBuilder
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationKeyComparer.html
  name: ConfigurationKeyComparer
  nameWithType: ConfigurationKeyComparer
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
- uid: Microsoft.Extensions.Configuration.ConfigurationManager
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationManager
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationManager.html
  name: ConfigurationManager
  nameWithType: ConfigurationManager
  fullName: Microsoft.Extensions.Configuration.ConfigurationManager
- uid: Microsoft.Extensions.Configuration.ConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationProvider.html
  name: ConfigurationProvider
  nameWithType: ConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.ConfigurationProvider
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationReloadToken
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationReloadToken.html
  name: ConfigurationReloadToken
  nameWithType: ConfigurationReloadToken
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken
- uid: Microsoft.Extensions.Configuration.ConfigurationRoot
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationRoot
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationRoot.html
  name: ConfigurationRoot
  nameWithType: ConfigurationRoot
  fullName: Microsoft.Extensions.Configuration.ConfigurationRoot
- uid: Microsoft.Extensions.Configuration.ConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationSection
  isExternal: true
  href: Microsoft.Extensions.Configuration.ConfigurationSection.html
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: Microsoft.Extensions.Configuration.ConfigurationSection
- uid: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  commentId: T:Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions.html
  name: MemoryConfigurationBuilderExtensions
  nameWithType: MemoryConfigurationBuilderExtensions
  fullName: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
- uid: Microsoft.Extensions.Configuration.StreamConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.StreamConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.StreamConfigurationProvider.html
  name: StreamConfigurationProvider
  nameWithType: StreamConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.StreamConfigurationProvider
- uid: Microsoft.Extensions.Configuration.StreamConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.StreamConfigurationSource
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.StreamConfigurationSource.html
  name: StreamConfigurationSource
  nameWithType: StreamConfigurationSource
  fullName: Microsoft.Extensions.Configuration.StreamConfigurationSource
- uid: Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
  commentId: T:Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions.html
  name: EnvironmentVariablesExtensions
  nameWithType: EnvironmentVariablesExtensions
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
- uid: Microsoft.Extensions.Configuration.FileConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.FileConfigurationExtensions.html
  name: FileConfigurationExtensions
  nameWithType: FileConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.FileConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.FileConfigurationProvider.html
  name: FileConfigurationProvider
  nameWithType: FileConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationSource
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.FileConfigurationSource.html
  name: FileConfigurationSource
  nameWithType: FileConfigurationSource
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource
- uid: Microsoft.Extensions.Configuration.FileLoadExceptionContext
  commentId: T:Microsoft.Extensions.Configuration.FileLoadExceptionContext
  isExternal: true
  href: Microsoft.Extensions.Configuration.FileLoadExceptionContext.html
  name: FileLoadExceptionContext
  nameWithType: FileLoadExceptionContext
  fullName: Microsoft.Extensions.Configuration.FileLoadExceptionContext
- uid: Microsoft.Extensions.Configuration.JsonConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.JsonConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.JsonConfigurationExtensions.html
  name: JsonConfigurationExtensions
  nameWithType: JsonConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.JsonConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions.html
  name: UserSecretsConfigurationExtensions
  nameWithType: UserSecretsConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.UserSecretsConfigurationExtensions
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Configuration.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Configuration.html
