### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration.Memory
  commentId: N:Microsoft.Extensions.Configuration.Memory
  id: Microsoft.Extensions.Configuration.Memory
  children:
  - Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  - Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration.Memory
  nameWithType: Microsoft.Extensions.Configuration.Memory
  fullName: Microsoft.Extensions.Configuration.Memory
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
  isExternal: true
  href: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider.html
  name: MemoryConfigurationProvider
  nameWithType: MemoryConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider
- uid: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
  parent: Microsoft.Extensions.Configuration.Memory
  isExternal: true
  href: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.html
  name: MemoryConfigurationSource
  nameWithType: MemoryConfigurationSource
  fullName: Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource
- uid: Microsoft.Extensions.Configuration.Memory
  commentId: N:Microsoft.Extensions.Configuration.Memory
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Extensions.Configuration.Memory
  nameWithType: Microsoft.Extensions.Configuration.Memory
  fullName: Microsoft.Extensions.Configuration.Memory
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Configuration.html
  - name: .
  - uid: Microsoft.Extensions.Configuration.Memory
    name: Memory
    isExternal: true
    href: Microsoft.Extensions.Configuration.Memory.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Configuration.html
  - name: .
  - uid: Microsoft.Extensions.Configuration.Memory
    name: Memory
    isExternal: true
    href: Microsoft.Extensions.Configuration.Memory.html
