### YamlMime:ManagedReference
items:
- uid: Serilog.LoggerSinkConfigurationDebugExtensions
  commentId: T:Serilog.LoggerSinkConfigurationDebugExtensions
  id: LoggerSinkConfigurationDebugExtensions
  parent: Serilog
  children:
  - Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Events.LogEventLevel,System.String,System.IFormatProvider,Serilog.Core.LoggingLevelSwitch)
  - Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Formatting.ITextFormatter,Serilog.Events.LogEventLevel,Serilog.Core.LoggingLevelSwitch)
  langs:
  - csharp
  - vb
  name: LoggerSinkConfigurationDebugExtensions
  nameWithType: LoggerSinkConfigurationDebugExtensions
  fullName: Serilog.LoggerSinkConfigurationDebugExtensions
  type: Class
  assemblies:
  - AccoRevit.Addin
  namespace: Serilog
  syntax:
    content: public static class LoggerSinkConfigurationDebugExtensions
    content.vb: Public Module LoggerSinkConfigurationDebugExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Events.LogEventLevel,System.String,System.IFormatProvider,Serilog.Core.LoggingLevelSwitch)
  commentId: M:Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Events.LogEventLevel,System.String,System.IFormatProvider,Serilog.Core.LoggingLevelSwitch)
  id: Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Events.LogEventLevel,System.String,System.IFormatProvider,Serilog.Core.LoggingLevelSwitch)
  isExtensionMethod: true
  parent: Serilog.LoggerSinkConfigurationDebugExtensions
  langs:
  - csharp
  - vb
  name: Debug(LoggerSinkConfiguration, LogEventLevel, string, IFormatProvider, LoggingLevelSwitch)
  nameWithType: LoggerSinkConfigurationDebugExtensions.Debug(LoggerSinkConfiguration, LogEventLevel, string, IFormatProvider, LoggingLevelSwitch)
  fullName: Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration, Serilog.Events.LogEventLevel, string, System.IFormatProvider, Serilog.Core.LoggingLevelSwitch)
  type: Method
  assemblies:
  - AccoRevit.Addin
  namespace: Serilog
  syntax:
    content: public static LoggerConfiguration Debug(this LoggerSinkConfiguration sinkConfiguration, LogEventLevel restrictedToMinimumLevel = LogEventLevel.Verbose, string outputTemplate = "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}", IFormatProvider formatProvider = null, LoggingLevelSwitch levelSwitch = null)
    parameters:
    - id: sinkConfiguration
      type: Serilog.Configuration.LoggerSinkConfiguration
    - id: restrictedToMinimumLevel
      type: Serilog.Events.LogEventLevel
    - id: outputTemplate
      type: System.String
    - id: formatProvider
      type: System.IFormatProvider
    - id: levelSwitch
      type: Serilog.Core.LoggingLevelSwitch
    return:
      type: Serilog.LoggerConfiguration
    content.vb: Public Shared Function Debug(sinkConfiguration As LoggerSinkConfiguration, restrictedToMinimumLevel As LogEventLevel = LogEventLevel.Verbose, outputTemplate As String = "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}", formatProvider As IFormatProvider = Nothing, levelSwitch As LoggingLevelSwitch = Nothing) As LoggerConfiguration
  overload: Serilog.LoggerSinkConfigurationDebugExtensions.Debug*
  nameWithType.vb: LoggerSinkConfigurationDebugExtensions.Debug(LoggerSinkConfiguration, LogEventLevel, String, IFormatProvider, LoggingLevelSwitch)
  fullName.vb: Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration, Serilog.Events.LogEventLevel, String, System.IFormatProvider, Serilog.Core.LoggingLevelSwitch)
  name.vb: Debug(LoggerSinkConfiguration, LogEventLevel, String, IFormatProvider, LoggingLevelSwitch)
- uid: Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Formatting.ITextFormatter,Serilog.Events.LogEventLevel,Serilog.Core.LoggingLevelSwitch)
  commentId: M:Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Formatting.ITextFormatter,Serilog.Events.LogEventLevel,Serilog.Core.LoggingLevelSwitch)
  id: Debug(Serilog.Configuration.LoggerSinkConfiguration,Serilog.Formatting.ITextFormatter,Serilog.Events.LogEventLevel,Serilog.Core.LoggingLevelSwitch)
  isExtensionMethod: true
  parent: Serilog.LoggerSinkConfigurationDebugExtensions
  langs:
  - csharp
  - vb
  name: Debug(LoggerSinkConfiguration, ITextFormatter, LogEventLevel, LoggingLevelSwitch)
  nameWithType: LoggerSinkConfigurationDebugExtensions.Debug(LoggerSinkConfiguration, ITextFormatter, LogEventLevel, LoggingLevelSwitch)
  fullName: Serilog.LoggerSinkConfigurationDebugExtensions.Debug(Serilog.Configuration.LoggerSinkConfiguration, Serilog.Formatting.ITextFormatter, Serilog.Events.LogEventLevel, Serilog.Core.LoggingLevelSwitch)
  type: Method
  assemblies:
  - AccoRevit.Addin
  namespace: Serilog
  syntax:
    content: public static LoggerConfiguration Debug(this LoggerSinkConfiguration sinkConfiguration, ITextFormatter formatter, LogEventLevel restrictedToMinimumLevel = LogEventLevel.Verbose, LoggingLevelSwitch levelSwitch = null)
    parameters:
    - id: sinkConfiguration
      type: Serilog.Configuration.LoggerSinkConfiguration
    - id: formatter
      type: Serilog.Formatting.ITextFormatter
    - id: restrictedToMinimumLevel
      type: Serilog.Events.LogEventLevel
    - id: levelSwitch
      type: Serilog.Core.LoggingLevelSwitch
    return:
      type: Serilog.LoggerConfiguration
    content.vb: Public Shared Function Debug(sinkConfiguration As LoggerSinkConfiguration, formatter As ITextFormatter, restrictedToMinimumLevel As LogEventLevel = LogEventLevel.Verbose, levelSwitch As LoggingLevelSwitch = Nothing) As LoggerConfiguration
  overload: Serilog.LoggerSinkConfigurationDebugExtensions.Debug*
references:
- uid: Serilog
  commentId: N:Serilog
  isExternal: true
  href: Serilog.html
  name: Serilog
  nameWithType: Serilog
  fullName: Serilog
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Serilog.LoggerSinkConfigurationDebugExtensions.Debug*
  commentId: Overload:Serilog.LoggerSinkConfigurationDebugExtensions.Debug
  isExternal: true
  href: Serilog.LoggerSinkConfigurationDebugExtensions.html#Serilog_LoggerSinkConfigurationDebugExtensions_Debug_Serilog_Configuration_LoggerSinkConfiguration_Serilog_Events_LogEventLevel_System_String_System_IFormatProvider_Serilog_Core_LoggingLevelSwitch_
  name: Debug
  nameWithType: LoggerSinkConfigurationDebugExtensions.Debug
  fullName: Serilog.LoggerSinkConfigurationDebugExtensions.Debug
- uid: Serilog.Configuration.LoggerSinkConfiguration
  commentId: T:Serilog.Configuration.LoggerSinkConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerSinkConfiguration.html
  name: LoggerSinkConfiguration
  nameWithType: LoggerSinkConfiguration
  fullName: Serilog.Configuration.LoggerSinkConfiguration
- uid: Serilog.Events.LogEventLevel
  commentId: T:Serilog.Events.LogEventLevel
  parent: Serilog.Events
  isExternal: true
  href: Serilog.Events.LogEventLevel.html
  name: LogEventLevel
  nameWithType: LogEventLevel
  fullName: Serilog.Events.LogEventLevel
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.IFormatProvider
  commentId: T:System.IFormatProvider
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iformatprovider
  name: IFormatProvider
  nameWithType: IFormatProvider
  fullName: System.IFormatProvider
- uid: Serilog.Core.LoggingLevelSwitch
  commentId: T:Serilog.Core.LoggingLevelSwitch
  parent: Serilog.Core
  isExternal: true
  href: Serilog.Core.LoggingLevelSwitch.html
  name: LoggingLevelSwitch
  nameWithType: LoggingLevelSwitch
  fullName: Serilog.Core.LoggingLevelSwitch
- uid: Serilog.LoggerConfiguration
  commentId: T:Serilog.LoggerConfiguration
  parent: Serilog
  isExternal: true
  href: Serilog.LoggerConfiguration.html
  name: LoggerConfiguration
  nameWithType: LoggerConfiguration
  fullName: Serilog.LoggerConfiguration
- uid: Serilog.Configuration
  commentId: N:Serilog.Configuration
  isExternal: true
  href: Serilog.html
  name: Serilog.Configuration
  nameWithType: Serilog.Configuration
  fullName: Serilog.Configuration
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Configuration
    name: Configuration
    isExternal: true
    href: Serilog.Configuration.html
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Configuration
    name: Configuration
    isExternal: true
    href: Serilog.Configuration.html
- uid: Serilog.Events
  commentId: N:Serilog.Events
  isExternal: true
  href: Serilog.html
  name: Serilog.Events
  nameWithType: Serilog.Events
  fullName: Serilog.Events
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Events
    name: Events
    isExternal: true
    href: Serilog.Events.html
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Events
    name: Events
    isExternal: true
    href: Serilog.Events.html
- uid: Serilog.Core
  commentId: N:Serilog.Core
  isExternal: true
  href: Serilog.html
  name: Serilog.Core
  nameWithType: Serilog.Core
  fullName: Serilog.Core
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Core
    name: Core
    isExternal: true
    href: Serilog.Core.html
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Core
    name: Core
    isExternal: true
    href: Serilog.Core.html
- uid: Serilog.Formatting.ITextFormatter
  commentId: T:Serilog.Formatting.ITextFormatter
  parent: Serilog.Formatting
  isExternal: true
  href: Serilog.Formatting.ITextFormatter.html
  name: ITextFormatter
  nameWithType: ITextFormatter
  fullName: Serilog.Formatting.ITextFormatter
- uid: Serilog.Formatting
  commentId: N:Serilog.Formatting
  isExternal: true
  href: Serilog.html
  name: Serilog.Formatting
  nameWithType: Serilog.Formatting
  fullName: Serilog.Formatting
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Formatting
    name: Formatting
    isExternal: true
    href: Serilog.Formatting.html
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Formatting
    name: Formatting
    isExternal: true
    href: Serilog.Formatting.html
