### YamlMime:ManagedReference
items:
- uid: AccoRevit.Addin.Settings
  commentId: N:AccoRevit.Addin.Settings
  id: AccoRevit.Addin.Settings
  children:
  - AccoRevit.Addin.Settings.PointLoadExportModel
  - AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate
  - AccoRevit.Addin.Settings.PointLoadExportSettings
  - AccoRevit.Addin.Settings.RecordStampModel
  - AccoRevit.Addin.Settings.RecordStampSettings
  - AccoRevit.Addin.Settings.TabColorizerSettings
  langs:
  - csharp
  - vb
  name: AccoRevit.Addin.Settings
  nameWithType: AccoRevit.Addin.Settings
  fullName: AccoRevit.Addin.Settings
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: AccoRevit.Addin.Settings.PointLoadExportSettings
  commentId: T:AccoRevit.Addin.Settings.PointLoadExportSettings
  isExternal: true
  href: AccoRevit.Addin.Settings.PointLoadExportSettings.html
  name: PointLoadExportSettings
  nameWithType: PointLoadExportSettings
  fullName: AccoRevit.Addin.Settings.PointLoadExportSettings
- uid: AccoRevit.Addin.Settings.PointLoadExportModel
  commentId: T:AccoRevit.Addin.Settings.PointLoadExportModel
  parent: AccoRevit.Addin.Settings
  isExternal: true
  href: AccoRevit.Addin.Settings.PointLoadExportModel.html
  name: PointLoadExportModel
  nameWithType: PointLoadExportModel
  fullName: AccoRevit.Addin.Settings.PointLoadExportModel
- uid: AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate
  commentId: T:AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate
  parent: AccoRevit.Addin.Settings
  isExternal: true
  href: AccoRevit.Addin.Settings.PointLoadExportModel.html
  name: PointLoadExportModel.Coordinate
  nameWithType: PointLoadExportModel.Coordinate
  fullName: AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate
  spec.csharp:
  - uid: AccoRevit.Addin.Settings.PointLoadExportModel
    name: PointLoadExportModel
    isExternal: true
    href: AccoRevit.Addin.Settings.PointLoadExportModel.html
  - name: .
  - uid: AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate
    name: Coordinate
    isExternal: true
    href: AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate.html
  spec.vb:
  - uid: AccoRevit.Addin.Settings.PointLoadExportModel
    name: PointLoadExportModel
    isExternal: true
    href: AccoRevit.Addin.Settings.PointLoadExportModel.html
  - name: .
  - uid: AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate
    name: Coordinate
    isExternal: true
    href: AccoRevit.Addin.Settings.PointLoadExportModel.Coordinate.html
- uid: AccoRevit.Addin.Settings.RecordStampSettings
  commentId: T:AccoRevit.Addin.Settings.RecordStampSettings
  isExternal: true
  href: AccoRevit.Addin.Settings.RecordStampSettings.html
  name: RecordStampSettings
  nameWithType: RecordStampSettings
  fullName: AccoRevit.Addin.Settings.RecordStampSettings
- uid: AccoRevit.Addin.Settings.RecordStampModel
  commentId: T:AccoRevit.Addin.Settings.RecordStampModel
  parent: AccoRevit.Addin.Settings
  isExternal: true
  href: AccoRevit.Addin.Settings.RecordStampModel.html
  name: RecordStampModel
  nameWithType: RecordStampModel
  fullName: AccoRevit.Addin.Settings.RecordStampModel
- uid: AccoRevit.Addin.Settings.TabColorizerSettings
  commentId: T:AccoRevit.Addin.Settings.TabColorizerSettings
  isExternal: true
  href: AccoRevit.Addin.Settings.TabColorizerSettings.html
  name: TabColorizerSettings
  nameWithType: TabColorizerSettings
  fullName: AccoRevit.Addin.Settings.TabColorizerSettings
- uid: AccoRevit.Addin.Settings
  commentId: N:AccoRevit.Addin.Settings
  isExternal: true
  href: AccoRevit.html
  name: AccoRevit.Addin.Settings
  nameWithType: AccoRevit.Addin.Settings
  fullName: AccoRevit.Addin.Settings
  spec.csharp:
  - uid: AccoRevit
    name: AccoRevit
    isExternal: true
    href: AccoRevit.html
  - name: .
  - uid: AccoRevit.Addin
    name: Addin
    isExternal: true
    href: AccoRevit.Addin.html
  - name: .
  - uid: AccoRevit.Addin.Settings
    name: Settings
    isExternal: true
    href: AccoRevit.Addin.Settings.html
  spec.vb:
  - uid: AccoRevit
    name: AccoRevit
    isExternal: true
    href: AccoRevit.html
  - name: .
  - uid: AccoRevit.Addin
    name: Addin
    isExternal: true
    href: AccoRevit.Addin.html
  - name: .
  - uid: AccoRevit.Addin.Settings
    name: Settings
    isExternal: true
    href: AccoRevit.Addin.Settings.html
