### YamlMime:ManagedReference
items:
- uid: Microsoft.CodeAnalysis.RulesetToEditorconfig
  commentId: N:Microsoft.CodeAnalysis.RulesetToEditorconfig
  id: Microsoft.CodeAnalysis.RulesetToEditorconfig
  children:
  - Microsoft.CodeAnalysis.RulesetToEditorconfig.Converter
  langs:
  - csharp
  - vb
  name: Microsoft.CodeAnalysis.RulesetToEditorconfig
  nameWithType: Microsoft.CodeAnalysis.RulesetToEditorconfig
  fullName: Microsoft.CodeAnalysis.RulesetToEditorconfig
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.CodeAnalysis.RulesetToEditorconfig.Converter
  commentId: T:Microsoft.CodeAnalysis.RulesetToEditorconfig.Converter
  isExternal: true
  href: Microsoft.CodeAnalysis.RulesetToEditorconfig.Converter.html
  name: Converter
  nameWithType: Converter
  fullName: Microsoft.CodeAnalysis.RulesetToEditorconfig.Converter
