### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Logging.Configuration
  commentId: N:Microsoft.Extensions.Logging.Configuration
  id: Microsoft.Extensions.Logging.Configuration
  children:
  - Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfigurationFactory
  - Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration`1
  - Microsoft.Extensions.Logging.Configuration.LoggerProviderOptions
  - Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource`2
  - Microsoft.Extensions.Logging.Configuration.LoggingBuilderConfigurationExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Logging.Configuration
  nameWithType: Microsoft.Extensions.Logging.Configuration
  fullName: Microsoft.Extensions.Logging.Configuration
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration`1
  commentId: T:Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration`1
  isExternal: true
  href: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration-1.html
  name: ILoggerProviderConfiguration<T>
  nameWithType: ILoggerProviderConfiguration<T>
  fullName: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration<T>
  nameWithType.vb: ILoggerProviderConfiguration(Of T)
  fullName.vb: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration(Of T)
  name.vb: ILoggerProviderConfiguration(Of T)
  spec.csharp:
  - uid: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration`1
    name: ILoggerProviderConfiguration
    isExternal: true
    href: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration`1
    name: ILoggerProviderConfiguration
    isExternal: true
    href: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfigurationFactory
  commentId: T:Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfigurationFactory
  isExternal: true
  href: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfigurationFactory.html
  name: ILoggerProviderConfigurationFactory
  nameWithType: ILoggerProviderConfigurationFactory
  fullName: Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfigurationFactory
- uid: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptions
  commentId: T:Microsoft.Extensions.Logging.Configuration.LoggerProviderOptions
  isExternal: true
  href: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptions.html
  name: LoggerProviderOptions
  nameWithType: LoggerProviderOptions
  fullName: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptions
- uid: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource`2
  commentId: T:Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource`2
  isExternal: true
  href: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource-2.html
  name: LoggerProviderOptionsChangeTokenSource<TOptions, TProvider>
  nameWithType: LoggerProviderOptionsChangeTokenSource<TOptions, TProvider>
  fullName: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource<TOptions, TProvider>
  nameWithType.vb: LoggerProviderOptionsChangeTokenSource(Of TOptions, TProvider)
  fullName.vb: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource(Of TOptions, TProvider)
  name.vb: LoggerProviderOptionsChangeTokenSource(Of TOptions, TProvider)
  spec.csharp:
  - uid: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource`2
    name: LoggerProviderOptionsChangeTokenSource
    isExternal: true
    href: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource-2.html
  - name: <
  - name: TOptions
  - name: ','
  - name: " "
  - name: TProvider
  - name: '>'
  spec.vb:
  - uid: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource`2
    name: LoggerProviderOptionsChangeTokenSource
    isExternal: true
    href: Microsoft.Extensions.Logging.Configuration.LoggerProviderOptionsChangeTokenSource-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TOptions
  - name: ','
  - name: " "
  - name: TProvider
  - name: )
- uid: Microsoft.Extensions.Logging.Configuration.LoggingBuilderConfigurationExtensions
  commentId: T:Microsoft.Extensions.Logging.Configuration.LoggingBuilderConfigurationExtensions
  parent: Microsoft.Extensions.Logging.Configuration
  isExternal: true
  href: Microsoft.Extensions.Logging.Configuration.LoggingBuilderConfigurationExtensions.html
  name: LoggingBuilderConfigurationExtensions
  nameWithType: LoggingBuilderConfigurationExtensions
  fullName: Microsoft.Extensions.Logging.Configuration.LoggingBuilderConfigurationExtensions
- uid: Microsoft.Extensions.Logging.Configuration
  commentId: N:Microsoft.Extensions.Logging.Configuration
  isExternal: true
  href: Microsoft.html
  name: Microsoft.Extensions.Logging.Configuration
  nameWithType: Microsoft.Extensions.Logging.Configuration
  fullName: Microsoft.Extensions.Logging.Configuration
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: Microsoft.Extensions.Logging.html
  - name: .
  - uid: Microsoft.Extensions.Logging.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Logging.Configuration.html
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: Microsoft.html
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: Microsoft.Extensions.html
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: Microsoft.Extensions.Logging.html
  - name: .
  - uid: Microsoft.Extensions.Logging.Configuration
    name: Configuration
    isExternal: true
    href: Microsoft.Extensions.Logging.Configuration.html
