### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Diagnostics.Metrics.Configuration
  commentId: N:Microsoft.Extensions.Diagnostics.Metrics.Configuration
  id: Microsoft.Extensions.Diagnostics.Metrics.Configuration
  children:
  - Microsoft.Extensions.Diagnostics.Metrics.Configuration.IMetricListenerConfigurationFactory
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Diagnostics.Metrics.Configuration
  nameWithType: Microsoft.Extensions.Diagnostics.Metrics.Configuration
  fullName: Microsoft.Extensions.Diagnostics.Metrics.Configuration
  type: Namespace
  assemblies:
  - AccoRevit.Addin
references:
- uid: Microsoft.Extensions.Diagnostics.Metrics.Configuration.IMetricListenerConfigurationFactory
  commentId: T:Microsoft.Extensions.Diagnostics.Metrics.Configuration.IMetricListenerConfigurationFactory
  isExternal: true
  href: Microsoft.Extensions.Diagnostics.Metrics.Configuration.IMetricListenerConfigurationFactory.html
  name: IMetricListenerConfigurationFactory
  nameWithType: IMetricListenerConfigurationFactory
  fullName: Microsoft.Extensions.Diagnostics.Metrics.Configuration.IMetricListenerConfigurationFactory
